"""add index on user sermons

Revision ID: 16b1b1badb23
Revises: 6b6b9b2cc722
Create Date: 2026-08-31 13:18:47.752558

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16b1b1badb23"
down_revision: str | Sequence[str] | None = "6b6b9b2cc722"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_user_sermons_user_id_saved_at", "user_sermons", ["user_id", "saved_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_sermons_user_id_saved_at", table_name="user_sermons")
    # ### end Alembic commands ###
